services:
  - type: web
    name: fronta
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      python manage.py migrate &&
      gunicorn fronta.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: DEBUG
        value: "False"